import type { Config } from 'tailwindcss'

// DESIGN.md(Kinetic Enterprise) 토큰을 시맨틱 Tailwind 토큰으로 매핑(FR-1.4, DR-1).
// raw hex 사용 금지 — 컴포넌트는 시맨틱 클래스(text-on-surface, bg-primary 등)만 사용.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    // DESIGN.md 반응형 그리드와 정합(Mobile 4 / Tablet 8 / Desktop 12 컬럼).
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    extend: {
      colors: {
        surface: '#fbf9f9',
        'surface-dim': '#dbdad9',
        'surface-bright': '#fbf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e7',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#434751',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        outline: '#747782',
        'outline-variant': '#c4c6d2',
        'surface-tint': '#395da2',
        primary: '#00204e',
        'on-primary': '#ffffff',
        'primary-container': '#003478',
        'on-primary-container': '#7d9fe9',
        'inverse-primary': '#aec6ff',
        secondary: '#005db7',
        'on-secondary': '#ffffff',
        'secondary-container': '#599bfe',
        'on-secondary-container': '#003268',
        tertiary: '#4d000a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#750015',
        'on-tertiary-container': '#ff7576',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#aec6ff',
        'on-primary-fixed': '#001a43',
        'on-primary-fixed-variant': '#1c4489',
        'secondary-fixed': '#d6e3ff',
        'secondary-fixed-dim': '#a9c7ff',
        'on-secondary-fixed': '#001b3d',
        'on-secondary-fixed-variant': '#00468c',
        'tertiary-fixed': '#ffdad8',
        'tertiary-fixed-dim': '#ffb3b1',
        'on-tertiary-fixed': '#410007',
        'on-tertiary-fixed-variant': '#92001c',
        background: '#fbf9f9',
        'on-background': '#1b1c1c',
        'surface-variant': '#e3e2e2',
        'surface-light': '#f8f9fa',
        'surface-border': '#dcdcdc',
        'text-primary': '#000000',
        'text-secondary': '#555555',
        'text-disabled': '#bebebe',
        'accent-red': '#e63946',
      },
      fontFamily: {
        sans: ['"Hanken Grotesk"', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      spacing: {
        // 4px 베이스 증분(DESIGN.md)
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      zIndex: {
        map: '0',
        chrome: '10',
        overlay: '20',
        popup: '30',
        chat: '40',
        toast: '50',
      },
    },
  },
  plugins: [],
} satisfies Config
